version: '3.7'
services:
  haproxy:
    image: ${ha_image}
    container_name: minio-ha
    restart: unless-stopped
    ports:
      - "${ha_port}:4000"
      - "${ha_minio}:${ha_minio}"
    volumes: 
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    command: |
      haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    healthcheck:
      test: |
        [ `ps -ef|grep -v ps|wc -l` -ge 1 ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio1:
    image: ${minio_image}
    container_name: minio1
    restart: unless-stopped
    env_file: .env
    volumes:
      - minio1-1:/data1
      - minio1-2:/data2
      - minio1:/data
    ports:
      - "${minio1_port}:9000"
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: ${minio_access}
      MINIO_SECRET_KEY: ${minio_secret}
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: ${minio_image}
    container_name: minio2
    restart: unless-stopped
    env_file: .env
    volumes:
      - minio2-1:/data1
      - minio2-2:/data2
      - minio2:/data
    ports:
      - "${minio2_port}:9000"
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: ${minio_access}
      MINIO_SECRET_KEY: ${minio_secret}
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: ${minio_image}
    container_name: minio3
    restart: unless-stopped
    env_file: .env
    volumes:
      - minio3-1:/data1
      - minio3-2:/data2
      - minio3:/data
    ports:
      - "${minio3_port}:9000"
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: ${minio_access}
      MINIO_SECRET_KEY: ${minio_secret}
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: ${minio_image}
    container_name: minio4
    restart: unless-stopped
    env_file: .env
    volumes:
      - minio4-1:/data1
      - minio4-2:/data2
      - minio4:/data
    ports:
      - "${minio4_port}:9000"
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: ${minio_access}
      MINIO_SECRET_KEY: ${minio_secret}
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio1:
  minio2:
  minio3:
  minio4:
  minio1-1:
  minio1-2:
  minio2-1:
  minio2-2:
  minio3-1:
  minio3-2:
  minio4-1:
  minio4-2:
