version: '3'
services:
  haproxy:
    image: haproxy:alpine
    container_name: zkc-haproxy
    restart: unless-stopped
    ports:
      - 4000:4000
      - 2181:2181
    volumes: 
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    command: |
      haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    healthcheck:
      test: |
        [ `ps -ef|grep -v ps|wc -l` -ge 1 ]
      interval: 30s
      timeout: 20s
      retries: 3

  zoo1:
    image: zookeeper:latest
    container_name: zkc-zoo1
    restart: always
    container_name: zoo1
    expose:
      - "2181"
    # ports:
      # - "2182:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:latest
    container_name: zkc-zoo2
    restart: always
    container_name: zoo2
    expose:
      - "2181"
    # ports:
      # - "2183:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:latest
    container_name: zkc-zoo3
    restart: always
    container_name: zoo3
    expose:
      - "2181"
    # ports:
      # - "2184:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

